baseURL = "https://leportella.com"
theme = "tella"
defaultContentLanguage = "en"
copyright = "Everything is mine"
googleAnalytics = "UA-106178084-1"
disqusShoortname = "leportella-com"
title = "Leticia Portella's thoughts and learnings"
description = "I'm a happy dev, in love with data science that loves to write technical posts about tech, career and life."

[params]
metaDescription = "I'm a happy dev, in love with data science that loves to write technical posts about what tech, career and life."


[permalinks]
posts = "/:slug/"

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2

[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en"
    languageName = "English"
    [languages.en.params]
        about = "About me"
        about_text = "A happy dev, in love with data science. I write about technology, career and life."
        table_of_contents = "Topics"
        readin = "Read in"
        flag = "ğŸ‡®ğŸ‡ª"
        similar_posts = "Check posts in similar categories"
        cheers = "Cheers!"
        book = "My new book is here!"
        book_text = "It's a book about software development for people that donâ€™t have a background in computer science but want to know more about this world, even if they donâ€™t want to be developers! Available"
        book_link="https://fdly.li/buy"
        book_link_text="for pre-sale here"
    [[languages.en.menu.left]]
        name = "Home"
        url = "/"
        weight = 1
    [[languages.en.menu.left]]
        name = "Wiki"
        url = "/wiki"
        weight = 1
    [[languages.en.menu.left]]
        name = "Travel"
        url = "/travel"
        weight = 1
    [[languages.en.menu.left]]
        name = "ğŸ‡®ğŸ‡ª En"
        url = "/"
        weight = 1
    [[languages.en.menu.left]]
        name = "ğŸ‡§ğŸ‡· Pt"
        url = "/pt-br"
        weight = 2
    [[languages.en.menu.left]]
        name = "ğŸ‡ªğŸ‡¸ Es"
        url = "/es"
        weight = 3
    [[languages.en.menu.right]]
        name = "About"
        url = "/about"
        weight = 2
    [[languages.en.menu.right]]
        name = "Book"
        url = "/book"
        weight = 3
    [[languages.en.menu.right]]
        name = "Buy me a â˜•ï¸"
        url = "https://www.buymeacoffee.com/leportella"
        weight = 4
    [[languages.en.menu.right]]
        name = "Categories"
        url = "/categories"
        weight = 5
  [languages.pt-br]
    weight = 2
    contentDir = "content/pt-br"
    languageName = "PortuguÃªs"
    [languages.pt-br.params]
        about = "Sobre mim"
        about_text = "Uma deva feliz e apaixonada por ciÃªncia de dados. Escrevo sobre tecnologia, carreira e vida."
        table_of_contents = "TÃ³picos"
        readin = "Leia em"
        flag = "ğŸ‡§ğŸ‡·"
        similar_posts = "Textos em categorias semelhantes"
        cheers = "AbraÃ§o!"
        book = "Meu novo livro chegou!"
        book_text = "Ã‰ um livro sobre desenvolvimento de software para quem nÃ£o Ã© da Ã¡rea e quer saber mais sobre esse mundo, mesmo que ela nÃ£o queira se tornar uma desenvolvedora! JÃ¡ estÃ¡ disponÃ­vel"
        book_link="https://fdly.li/venda"
        book_link_text="na prÃ©-venda!"
    [[languages.pt-br.menu.left]]
        name = "InÃ­cio"
        url = "/pt-br"
        weight = 1
    [[languages.pt-br.menu.left]]
        name = "Wiki"
        url = "/wiki"
        weight = 1
    [[languages.pt-br.menu.left]]
        name = "ğŸ‡®ğŸ‡ª En"
        url = "/"
        weight = 1
    [[languages.pt-br.menu.left]]
        name = "ğŸ‡§ğŸ‡· Pt"
        url = "/pt-br"
        weight = 2
    [[languages.pt-br.menu.left]]
        name = "ğŸ‡ªğŸ‡¸ Es"
        url = "/es"
        weight = 3
    [[languages.pt-br.menu.right]]
        name = "Sobre"
        url = "/pt-br/about"
        weight = 2
    [[languages.pt-br.menu.right]]
        name = "Me pague um â˜•ï¸"
        url = "https://www.buymeacoffee.com/leportella"
        weight = 3
    [[languages.pt-br.menu.right]]
        name = "Categorias"
        url = "/pt-br/categories"
        weight = 4
    [[languages.pt-br.menu.right]]
        name = "ğŸ•"
        url = "https://pizzadedados.com/"
        weight = 5
  [languages.es]
    weight = 3
    contentDir = "content/es"
    languageName = "EspaÃ±ol"
    [languages.es.params]
        about = "Sobre mi"
        about_text = "Una desarrolladora feliz y apasionada de la ciencia de datos. Escribo sobre tecnologÃ­a, carrera y vida."
        table_of_contents = "Temas"
        readin = "Leer en"
        flag = "ğŸ‡ªğŸ‡¸"
        similar_posts = "Textos en categorÃ­as similares"
        cheers = "Abrazo!"
        book = "My new book is here!"
        book_text = "It's a book about software development for people that donâ€™t have a background in computer science but want to know more about this world, even if they donâ€™t want to be developers. Available"
        book_link="https://fdly.li/buy"
        book_link_text="here"
    [[languages.es.menu.left]]
        name = "Home"
        url = "/es"
        weight = 1
    [[languages.es.menu.left]]
        name = "Wiki"
        url = "/wiki"
        weight = 1
    [[languages.es.menu.left]]
        name = "ğŸ‡®ğŸ‡ª En"
        url = "/"
        weight = 1
    [[languages.es.menu.left]]
        name = "ğŸ‡§ğŸ‡· Pt"
        url = "/pt-br"
        weight = 2
    [[languages.es.menu.left]]
        name = "ğŸ‡ªğŸ‡¸ Es"
        url = "/es"
        weight = 3
    [[languages.es.menu.right]]
        name = "About"
        url = "/about"
        weight = 2
    [[languages.es.menu.right]]
        name = "Comprame un â˜•ï¸"
        url = "https://www.buymeacoffee.com/leportella"
        weight = 2
    [[languages.es.menu.right]]
        name = "Categories"
        url = "/categories"
        weight = 3
    [[languages.es.menu.right]]
        name = "Contact"
        url = "/contact"
        weight = 4
