baseURL = "http://example.org/"
theme = "tella"
defaultContentLanguage = "en"
copyright = "Everything is mine"

[permalinks]
posts = "/:slug/"

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    contentDir = "content/en"
    languageName = "English"
    [languages.en.params]
        readin = "Read in"
        flag = "ğŸ‡®ğŸ‡ª"
  [languages.pt-br]
    title = "Meu blog"
    weight = 2
    contentDir = "content/pt-br"
    languageName = "PortuguÃªs"
        [languages.pt-br.params]
        readin = "Leia em"
        flag = "ğŸ‡§ğŸ‡·"

[menu]
[[menu.left]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.left]]
identifier = "blog"
name = "ğŸ‡§ğŸ‡· Em PortuguÃªs"
url = "/pt-br/"
weight = 2

[[menu.right]]
identifier = "about"
name = "About"
url = "/about"
weight = 1